### ISSUE TITLE
More sensors!

### ISSUE THREAD

**Issue by Fettkeewl** [bj00rn/ha-saleryd-ftx#49]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to automate and configure UI based on the value of 
* Electric heater (if its enabled/disabled) 
* Target temperature on Normal/Cooling/Economy mode

**Describe the solution you'd like**
Create 4 new sensors that display the state of the above mentioned data
(or make the heater a switch if possible, that is "unavailable" unless maintenance PW is provided)

**Describe alternatives you've considered**
I've manually set temperatures for the different modes in UI elements, which
requires manual syncing with the settings in my LOKE-01

**Additional context**

**Comment by bj00rn** [comment]
Services for target temperature are implemented i v4 release

I've been a bit reluctant to add expose stuff from maintenance page until now, the potential for user to f**k up and potentially destroy the house with mould by overpressure. Disabling the electric heater may cause the system to shut down if supply air temperature alarm triggers. The initial scope of the integration was not to alter the system settings. I'll consider it though.

**Comment by Fettkeewl** [comment]
> I've been a bit reluctant to expose stuff from maintenance page until now, the potential for user to f**k up and potentially destroy the house with mould by overpressure.

In regards to this I understand you if we are talking control-ability, but purely for sensor use then it's no issue right? :)

**Comment by bj00rn** [comment]
> > I've been a bit reluctant to expose stuff from maintenance page until now, the potential for user to f**k up and potentially destroy the house with mould by overpressure.
> 
> In regards to this I understand you if we are talking control-ability, but purely for sensor use then it's no issue right? :)

Correct! The websocket connection streams all values including installer/maintenance configuration every few seconds to the client, the integration is just listening in on the data and exposing the values as sensors in HA.

I believe changing stuff like vent mode etc is not persisted on the device and (hopefully) shouldn’t cause any storage wear. 

Installer settings on the other hand, are persisted to flash. From the specs of ESP32 (if this is the case) the device should be good for around 10k-100k writes to flash.

**Comment by Fettkeewl** [comment]
Id love to reopen this if possible

I still want 3 new sensors: 
* 1 representing the setting for "normal temperature"
* 1 representing the setting for "economy temperature" 
* 1 representing the setting for "cooling temperature"
