### ISSUE TITLE
Service call change temp broken 

### ISSUE THREAD

**Issue by Fettkeewl** [bj00rn/ha-saleryd-ftx#60]
Hi Björn
I have a weird one for you. Late now so can't do a deep dive. Hope the video is sufficient for now

Basically use service to set target temp but ends up turning on cool mode instead of changing temperature 😅

https://github.com/user-attachments/assets/57171a89-7f16-41b6-ab0f-60b9e6b74477

**Comment by bj00rn** [comment]
Thanks! Probably a typo. I’ll check

**Comment by bj00rn** [comment]
> Hi Björn I have a weird one for you. Late now so can't do a deep dive. Hope the video is sufficient for now
> 
> Basically use service to set target temp but ends up turning on cool mode instead of changing temperature 😅
> 
>  Screen_Recording_20241128_212150_Chrome.mp4

Yup, https://github.com/bj00rn/ha-saleryd-ftx/blob/7a843163667dffaf331bcc944fe9f3d72d38081f/custom_components/saleryd_hrv/__init__.py#L174

I’ll get it fixed. Good catch
